### ISSUE TITLE
cert ssl unknown option 

### ISSUE THREAD

**Issue by sinalpha** [sinalpha/sinalpha.github.io#158]
``` ruby
➜  snippets git:(master) ✗ ruby ssl_server.rb
........++++++
.................++++++
/Users/wutuofu/.rbenv/versions/2.2.3/lib/ruby/2.2.0/openssl/x509.rb:26:in `create_ext': authorityKeyIdentifier = Keyid:always,issuer:always: unknown option (OpenSSL::X509::ExtensionError)
    from /Users/wutuofu/.rbenv/versions/2.2.3/lib/ruby/2.2.0/openssl/x509.rb:26:in `create_extension'
    from ssl_server.rb:64:in `create_self_signed_cert'
    from ssl_server.rb:10:in `main'
    from ssl_server.rb:70:in `<main>'
```

把`Keyid:always,issuer:always`改为`keyid:always,issuer:always`就没有报错了。

**Comment by sinalpha** [comment]
另外，贴下两个源码：

~~~
require 'rubygems'
require 'openssl'

key = OpenSSL::PKey::RSA.new(1024)
public_key = key.public_key

subject = "/C=BE/O=Test/OU=Test/CN=Test"

cert = OpenSSL::X509::Certificate.new
cert.subject = cert.issuer = OpenSSL::X509::Name.parse(subject)
cert.not_before = Time.now
cert.not_after = Time.now + 365 * 24 * 60 * 60
cert.public_key = public_key
cert.serial = 0x0
cert.version = 2

ef = OpenSSL::X509::ExtensionFactory.new
ef.subject_certificate = cert
ef.issuer_certificate = cert
cert.extensions = [
  ef.create_extension("basicConstraints","CA:TRUE", true),
  ef.create_extension("subjectKeyIdentifier", "hash"),
  # ef.create_extension("keyUsage", "cRLSign,keyCertSign", true),
]
cert.add_extension ef.create_extension("authorityKeyIdentifier",
                                       "keyid:always,issuer:always")

cert.sign key, OpenSSL::Digest::SHA1.new

puts cert.to_pem
~~~

[self_signed_cert.rb](https://gist.github.com/nickyp/886884)

另外一个是关于`socket`的：

~~~ruby 
require 'socket'
require 'openssl'

def main
  # Build the TCP server.
  server = TCPServer.new 4481

  # Build the SSL context.
  ctx = OpenSSL::SSL::SSLContext.new
  ctx.cert, ctx.key = create_self_signed_cert(
    1024,
    [['CN', 'localhost']],
    'Genetated by Ruby/OpenSSL lol'
  )
  ctx.verify_mode = OpenSSL::SSL::VERIFY_PEER

  # Build the SSL wrapper around the TCP server.
  ssl_server = OpenSSL::SSL::SSLServer.new server, ctx

  # Accept connections on the SSL socket.
  connection = ssl_server.accept

  # Treat it like any other connection.
  connection.write 'Bah now'
  connection.close
end

# This code is unabashedly taken straight from webrick/ssl.
# It genetates a self-signed SSL certificate suitable for use
# with a Context object.

def create_self_signed_cert(bits, cn, comment)
  rsa = OpenSSL::PKey::RSA.new(bits) do |p, n|
    case p
    when 0; $stderr.putc '.'  # BN_generate_prime
    when 1; $stderr.putc '+'  # BN_generate_prime
    when 2; $stderr.putc '*'  # searching good prime,
      # n = #of try,
      # but alse data from BN_generate_prime
    when 3; $stderr.putc "\n" # found good prime, n==0 - p, n==1 -q,
      # but also data from BN_generate_prime
    else; $stderr.putc '*'  # BN_generate_prime
    end
  end
  cert = OpenSSL::X509::Certificate.new
  cert.version = 2
  cert.serial = 1
  name = OpenSSL::X509::Name.new cn
  cert.issuer = name
  cert.subject = name
  cert.not_before = Time.now
  cert.not_after = Time.now + 365 * 24 * 60 * 60
  cert.public_key = rsa.public_key

  ef = OpenSSL::X509::ExtensionFactory.new nil, cert
  ef.issuer_certificate = cert
  cert.extensions = [
    ef.create_extension('basicConstraints', 'CA:FALSE'),
    ef.create_extension('keyUsage', 'keyEncipherment'),
    ef.create_extension('subjectKeyIdentifier', 'hash'),
    ef.create_extension('extendedKeyUsage', 'serverAuth'),
    ef.create_extension('nsComment', comment)]

  aki = ef.create_extension 'authorityKeyIdentifier', 'keyid:always,issuer:always'
  cert.add_extension aki
  cert.sign rsa, OpenSSL::Digest::SHA1.new
  return [ cert, rsa ]
end

main

~~~

raise
## (OpenSSL::SSL::SSLError)
~~~ruby
➜  snippets git:(master) ✗ ruby ssl_server.rb
..........++++++
..................................++++++
/Users/wutuofu/.rbenv/versions/2.2.3/lib/ruby/2.2.0/openssl/ssl.rb:306:in `accept': SSL_accept SYSCALL returned=5 errno=0 state=SSLv2/v3 read client hello A (OpenSSL::SSL::SSLError)
	from /Users/wutuofu/.rbenv/versions/2.2.3/lib/ruby/2.2.0/openssl/ssl.rb:306:in `accept'
	from ssl_server.rb:21:in `main'
	from ssl_server.rb:70:in `<main>'
~~~
