### ISSUE TITLE
不让rails某个model直接生产实例

### ISSUE THREAD

**Issue by sinalpha** [sinalpha/sinalpha.github.io#9]
ruby code

~~~
# only router can create ss_precesses
 27   def initialize
 28     #return 'cannot create ss_process without router' unless router
 29     #return Router.new.processes.new unless router
 30     #super unless router
 31   end

 after_save :start_process

def create_process_object
   return 'cannot create ss_process without router' unless router
   ....
end
~~~

rails console
~~~
➜  freeway_new git:(dev) rails c
Loading development environment (Rails 4.2.3)
[1] pry(main)> SsProcess.new
NoMethodError: undefined method `mac_address' for nil:NilClass
from /Users/wutuofu/bitbuck/freeway_new/app/models/ss_process.rb:52:in `create_process_object'
~~~

super 一下，发现并不ok

~~~
Loading development environment (Rails 4.2.3)
[1] pry(main)> SsProcess.new
NoMethodError: undefined method `[]' for nil:NilClass
from /Users/wutuofu/bitbuck/freeway_new/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/associations.rb:172:in `association_instance_get'
~~~

空的initialize方法是ok的

~~~

Loading development environment (Rails 4.2.3)
[1] pry(main)> SsProcess.new
=> #<SsProcess:0x007faf8eb45128 not initialized>
[2] pry(main)> m = SsProcess.new
=> #<SsProcess:0x007faf8eb2ee50 not initialized>
~~~

**Comment by sinalpha** [comment]
年代太久远，不能记得当初脑袋里面想得时什么了。
翻了下源码，结果并不是用的覆写initialize方法，而是调用了after_initialize 这个callback。

~~~

	after_initialize :create_process_object, if: :do_create_ss?


	private

	def create_process_object
		self.salt = SecureRandom.hex
		self.password = Digest::SHA1.hexdigest( router.some_attribute + salt )
		self.server = router.try :server
		generate_port
	end

	def do_create_ss?
		new_record? && router
	end

~~~
